name: gui
description: GUI tools
events:
    click:
        payload:
            x: number
            y: number
widgets:
    box:
        type: primitive
        attributes: ~
        children:
            # TODO - needs to allow any primitive or compound widget type, _but_ only if its eventual core widget
            #        would be valid - eg. an <li> HTML element cannot be nested as a direct child of a <div>
            contents: ~
        groups: [gui.primitive]
        events: [gui.click]
    button:
        type: primitive
        attributes: {label: text}
        children: [] # Buttons can have no children, only a label (TODO: allow icons?)
        groups: [gui.primitive]
        events: [gui.click]
    container:
        type: primitive
        children:
            contents: ~
        groups: [gui.primitive]
        events: [gui.click]
    heading:
        type: primitive
        attributes: {level: number}
        children:
            contents: ~
        groups: [gui.primitive]
        events: [gui.click]
    horizontal_rule:
        type: primitive
        groups: [gui.primitive]
        events: [gui.click]
    list:
        type: primitive
        attributes:
            ordered:
                type: boolean
                default: "=false"
        children:
            items: ~
        groups: [gui.primitive]
        events: [gui.click]
    list_item:
        type: primitive
        children:
            contents: ~
        groups: [gui.primitive]
        events: [gui.click]
    navigation:
        type: primitive
        children:
            contents: ~
        groups: [gui.primitive]
        events: [gui.click]
    route_link:
        type: compound
        attributes:
            route:
                type: exotic
                name: route_name
                arguments_static: arguments
            arguments:
                type: exotic
                name: route_arguments
                route_static: route
                default: "={}"
        children:
            contents: ~
        events: [gui.click]
        root:
            type: gui.url_link
            attributes:
                url: "=route_url(route: widget_attr('route'), arguments: widget_attr('arguments'))"
            children:
                contents:
                    type: child
                    name: contents
            triggers:
                gui.click:
                    instructions:
                        - type: navigate
                          route: "=widget_attr('route')"
                          arguments: "=widget_attr('arguments')"
    textbox:
        type: primitive
        attributes: {value: text}
        values:
            text:
                type: text
                default: "=widget_attr('value')"
        children: [] # Textboxes can have no children, as there is nowhere to render them
        groups: [gui.primitive]
        events: []
    url_link:
        type: primitive
        attributes: {url: text}
        children:
            contents: ~
        events: [gui.click]
